server:
  port: 9006

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://127.0.0.1/[LetiCoin]CourseServiceDB
    username: postgres
    password: 23922392
  jpa:
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

